dist: trusty
sudo: true
language: node_js
node_js: "node"
cache:
  directories:
  - node_modules
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get install wine1.6
install: true
script:
- npm run build
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/44f5607466509af53a93
    on_success: change
    on_failure: always
    on_start: never
before_deploy:
- npm run package
deploy:
  provider: releases
  api_key:
    secure: YNdqB6vdk3/xYHASJ1ZvwXKdqXDeJRHryEeI9Rx6dHk3MRmNgLRQIVDsKQuRUIWjXa4kpVxnuJbCV/HzpfFhhORKZoDRip9IpIcw6DOL9Muqx1Gc6Cb1T7D3cnl1cJ0WymcCUqieNQGUD/gHldfpqpQnydlPtJCEywoWSELEmRw2S1wNDnLjDStXJKPU4njkVlX0GealroK846DAEpHKgQ1aGqo0v6AAjmDK+iGE1avjo0J3VhL9Xlt9JaKrKhqBN4qcTVIc1sz2/7ygdtNEd3YikDCqA4av1kJa7eE9ai9+2r5AB7tpO4d4exWb9VG+2ZLmt6l2Ru7oDI7mD+Ns4shJ7Zo4q4cJfXZM9TGLYvEdV1xOQzAPFlB783J5oNQ/Efuo68BfVKkmq5GptAipQfQcDbMbqLEJBvjMTSXHpFJWw0I3NqQZc3n6wg30gRFi0xkt7eW4/Oig29DOY/RHwoTMRGGb3xz6StSR3kTYXghNpVotE6dy3QouAUbga9GQFsS/hWSa09mLYTDSrE9ThneDTXu3sTbHBoe08FiRr5Vvj+Tgk+8Wbk73G9UPnLbRSE1yvCO1im9u9qjmL9cd9XEQO14f6hcnxfx1D/vcuBbeYcGvX6fUyTmgWXFgLllPRTAsSdhgIT/9jLBBwkLrXuj93JeB+rcovEmzOrNWp8M=
  file_glob: true
  file: "packages/superpowers-*.zip"
  skip_cleanup: true
  draft: true
  on:
    repo: superpowers/superpowers-app
    tags: true
